[profile.default]
src = 'src'
test = 'test/'
out = 'out'
libs = ['lib']
solc_version = "0.8.18"
optimizer = true
optimizer_runs = 1_000_000

[fmt]
line_length = 80
number_underscore = "thousands"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}" 
optimism = "${OPTIMISM_RPC_URL}"
base = "${BASE_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
optimismSepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
optimism = { key = "${OPTIMISM_ETHERSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
optimismSepolia = { key = "${OPTIMISM_ETHERSCAN_API_KEY}" }
baseSepolia = { key = "${BASESCAN_API_KEY}" }